version: '3.8'

services:
  web:
    build: .
    env_file:
      - prod.env
    restart: always
    ports:
      - 8000:8000
    volumes:
      - .:/app
    depends_on:
      - db
      - redis

  db:
    image: postgres:16
    env_file:
      - prod.env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

  redis:
    image: redis:6.2
    env_file:
      - prod.env
    volumes:
      - redis_data:/data
    restart: always

volumes:
  postgres_data:
  redis_data: