version: '3.9'

services:
  web:
    build:
      context: .
      dockerfile: api/Dockerfile
    env_file:
      - api/.env
    restart: always
    ports:
      - 8000:8000
    volumes:
      - ./api:/app/api
    depends_on:
      - db
      - redis
  script:
    build:
      context: .
      dockerfile: scheduler/Dockerfile
    volumes:
      - ./scheduler:/app/scheduler
    depends_on:
      - web
    restart: always
    env_file:
      - scheduler/.env
  db:
    image: postgres:16
    env_file:
      - api/.env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always
    
  redis:
    image: redis:6.2
    env_file:
      - api/.env
    volumes:
      - redis_data:/data
    restart: always

volumes:
  postgres_data:
  redis_data: