"""first migration

Revision ID: a5dc095fe55c
Revises: 
Create Date: 2023-10-23 18:56:40.869919

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a5dc095fe55c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('timezone',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shift_seconds', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('volumes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rain_1h', sa.Float(), nullable=True),
    sa.Column('rain_3h', sa.Float(), nullable=True),
    sa.Column('snow_1h', sa.Float(), nullable=True),
    sa.Column('snow_3h', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('wind',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('speed', sa.Float(), nullable=True),
    sa.Column('deg', sa.Integer(), nullable=True),
    sa.Column('gust', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('location',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cityname', sa.String(), nullable=True),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('timezone_id', sa.Integer(), nullable=True),
    sa.Column('sunrise', sa.Integer(), nullable=True),
    sa.Column('sunset', sa.Integer(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['timezone_id'], ['timezone.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('weather_metrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('temp', sa.Float(), nullable=True),
    sa.Column('feels_like', sa.Float(), nullable=True),
    sa.Column('pressure', sa.Float(), nullable=True),
    sa.Column('visibility', sa.Integer(), nullable=True),
    sa.Column('cloudiness', sa.Integer(), nullable=True),
    sa.Column('wind_id', sa.Integer(), nullable=True),
    sa.Column('humidity', sa.Integer(), nullable=True),
    sa.Column('temp_min', sa.Float(), nullable=True),
    sa.Column('temp_max', sa.Float(), nullable=True),
    sa.Column('sea_level', sa.Float(), nullable=True),
    sa.Column('grnd_level', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['wind_id'], ['wind.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('current_weather',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=True),
    sa.Column('weather_metrics_id', sa.Integer(), nullable=True),
    sa.Column('volume_id', sa.Integer(), nullable=True),
    sa.Column('fetch_time', sa.DateTime(), nullable=True),
    sa.Column('dt_calculation', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['location_id'], ['location.id'], ),
    sa.ForeignKeyConstraint(['volume_id'], ['volumes.id'], ),
    sa.ForeignKeyConstraint(['weather_metrics_id'], ['weather_metrics.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('weather',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('main', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('icon', sa.String(), nullable=True),
    sa.Column('weather_metrics_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['weather_metrics_id'], ['weather_metrics.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('weather_association',
    sa.Column('current_weather_id', sa.Integer(), nullable=True),
    sa.Column('weather_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['current_weather_id'], ['current_weather.id'], ),
    sa.ForeignKeyConstraint(['weather_id'], ['weather.id'], )
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('weather_association')
    op.drop_table('weather')
    op.drop_table('current_weather')
    op.drop_table('weather_metrics')
    op.drop_table('location')
    op.drop_table('wind')
    op.drop_table('volumes')
    op.drop_table('timezone')
    # ### end Alembic commands ###
