name: Docker CI

on: [push, pull_request]

jobs:
  build:
    name: Build and Lint
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: lint
      run:  ./common/scripts/lint.sh
      continue-on-error: false
